name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}        
      run: |
        docker build . --file Dockerfile --tag vimalprakashts/ci-with-docker-test:1.0.1
        docker login -u DOCKER_USER -p DOCKER_PASSWORD
        docker push vimalprakashts/ci-with-docker-test:1.0.1
        
